name: "Build production Image"
on:
  push:
  workflow_call:
    inputs:
      tag:
        required: false
        default: ""
        description: 'Tag to deploy'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      tag:
        required: false
        default: ""
        description: 'Tag to deploy'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: go build  -v ./...

      - name: Test
        run: go test -v ./...
  container:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - id: detect_version
        run: |
            if [ "${{inputs.tag}}" == "" ]; then
            COMMIT=${GITHUB_SHA::7}
            echo "docker_tag=$COMMIT" >> $GITHUB_OUTPUT
            else 
            echo "docker_tag=${{inputs.tag}}" >> $GITHUB_OUTPUT
            fi
            ls -al 
      - uses: ForestsoftGmbH/gh-build-action@main
        with:
          DOCKER_IMAGE: forestsoft/devctl
          DOCKER_TAG: ${{steps.detect_version.outputs.docker_tag}}
          File: ./Dockerfile
          context: .
          Username: ${{ secrets.DOCKER_USERNAME }}
          Password: ${{ secrets.DOCKER_PASSWORD }}