name: Erstelle Release und weise Artefakte zu

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version:  ${{ steps.setup.outputs.version }}
      docker_tag:  ${{ steps.setup.outputs.docker_tag }}
    steps:
      - shell: bash
        id: setup
        run: |
         if [ "${{inputs.tag}}" == "" ]; then
         COMMIT=${GITHUB_SHA::7}
         echo "docker_tag=$COMMIT" >> $GITHUB_OUTPUT
         else 
         echo "docker_tag=${{inputs.tag}}" >> $GITHUB_OUTPUT
         fi
         version=$(echo "$COMMIT" | sed 's#refs/tags/##')
         echo "version=$COMMIT" >> $GITHUB_OUTPUT
  build:
    needs:
      - setup
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.setup.outputs.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Erstelle Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Erstelle Release
          draft: false
          prerelease: false

      - name: Artefakte hochladen
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./devctl
          asset_name: devctl
          asset_content_type: application/octet-stream
